language: java
before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
  - $HOME/.gradle/caches/
  - $HOME/.gradle/wrapper/
env:
  global:
  - secure: htzan1H+RYTRYq4UiyszZjPM36owM3j9+v2yU0oUznxvpZHZhTGYkDMkagyTyIiwePz+gg4IYW3Xcu4xhuG9RfMgykEtYFAwKFmIIe1i2XqX8utKFN0wcwgIuSmOLBCshSNCdb4pB0J2/oYdKO+r08AjqLqcM3rzsPMxzWvl4p6ewmOtIA5bKU8/JmJs1jV+lMn2VmXHW8sKX6de1ex3KI0gIH0coCbemGTFX7iPmXn7aG8VqDflGn+YjBulkS8rX2cQ8rH7zRfTMalRtNrl0hdQvwTDwaFN++dYnKWOf19R2ErGs4ouIsT5VAMSkvGNVrDaBBawQmyc9qydmki6Hb1MqjO/N1Lno0yEOk2ccc1T+eoZcqaD0Qe6rUtTJ8JOckbCxzMzlCp/j2A1GWGs+Kgp+j8TB8JW8i9rMZG4kA0uusk/IiVIrvaCxKcD8BJzBfijuPIPZUYA0gjeGyqrnjjZQBVkkam6EhBvaWoLbjDGWAngJO16vFTq6bf8jJUFEtuSWseWMXg4EV+nj/C8+J92dtwxBQTy0horQsTNkt2+FKQN6PMFFLNM572P7VUQMts7OeDIeKcrUXb0Lpa6RFtuVj9NPCpq9Aaf1FqhGISVq/JMbYOLeAG15iMKokev2srye6AQ+s/T9sEmjgSdB6Tu2fr8RFmqmYVNKd2PpaI=
  - secure: Cz84smuIbnOJhigQhL2wx/6RxgIIOBn1hfO0wBqGmCC8C31u7J6zTgMAXV/4vTR3wYpUM91H4CNsmOj167uf5suLZYNYIIYuvH0rYmbzYHRQ/jYDNPfH07VPHo+deyjVZ99DPRXZdef/d7xDa9Tz7GcVX52uVh1XmhKN4YwkFBeTLIzBTGonnls8fxu8t/Y+tD0j5RK85zZvIHg90u0vziVi6eRBmrrZ2v1l0Ec342Kc4sGa6zwbWTzKV9hjmIy3oNVLrKytOD17A6nw/0cwWMtmGgDmWKfxpiEceDmHahcebV5XI4i9q7Oa0384XRMVo5tosJW/76qC0oxXJWynmmyMQ6rkInB9/gf6ehkZ/PxLP6bG5M1gcO46q73Y4AX0LmZU8f+UGRXZKw6nQg3DJnXfDMc5IxNIKsS7Xc+EUbtBWt2iOwhw0AN6DXj1A0hicHO4Ig9teKH04tsiwy2KnjMgXIyZrQpaIMFkaFbKsupglvFsD2RnPeIw40KAcAkkFtTpr/jtPUj+ddb79LLoytPL/TH3gqmgPbng91V63TwXUQgnVjcc5tJuUzanIao1Y1jzYe8dqQ41kYe/NLAI17uCj2SO4ZuIo5RPGUv7Zs3LBeyHCmmAMDWwvm1SW6naRJzt5HvAwIDESqeElDqf/Hb2N7TT56XNFN09x2qTSKo=
deploy:
- provider: script
  script: ./gradlew bintrayUpload --info
  skip_cleanup: true
  on:
    tags: true
- provider: releases
  api_key:
    secure: Yn/LzWkLp7ho0nemFOLBrwdjKeIjmCDHwGDUpGqzghsbEHrU2rfAR/uQDDqDZSwL+rJLdUugULLP1eG/VbzKJXpA7rOmfZ2GzuVDWbDAtMrFVSri9PYFcun9nnsthANZ6V098iDgiES/Kf/bLuOKCEjRDSfPfHtcO0PleCa2zOfr5cgeGMpRlwXTbDEhliviG8yHmp4Is1JNHd3CTjeevHscdr3UIzl4DBHlGAHh1yfI+BnicWI5/hDnw5T1KKVlWpe5PWAIbgrnabzvc7amV+EpRNxMtZ+p6qkcteXow8d9C5Yws0vZry9my8n467I76388wEIIGjMuS1jWk+VYhdPO5AuYJb+SO2QY0G6+VymE4KgDMHw8fLhUoKeFceMMTlpk4CiZIDlXQxrLFmWj53P31dfWP/OF4G05skDi5Fp1U37Fbiat3i3WomhrIgdA1mGyf9CbtqpD1A2Mbt19kUz0ZHMDCtxRkOw1ALFzzhdLolJy6WwmhmErmiZEO5E2RKMMdoXVx8elsjphnxekcJ8qRyHlQ/bpm3vG27Vzfm3HgBylTwXQ0gWvlHcVLD98OrsQNtQvPcfTcvu3DRvDAJvySS7LhCI9SNH28nfBUpebi0gYflvC9crHSGNk+z3kDrGnO1RT4S2pta47i7iHfhhneAgX5/d1QyJDQ3X7chg=
  file_glob: true
  file: build/libs/service-auth-provider-*.jar
  skip_cleanup: true
  on:
    repo: hmcts/service-auth-provider-java-client
    tags: true
