language: java
before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
  - $HOME/.gradle/caches/
  - $HOME/.gradle/wrapper/
script:
  - ./gradlew test
  - ./gradlew integration
env:
  global:
  - secure: Nek/L/91J2HOSicMxQWk7O5qNIQsxqSA2H/s3aAtvNKNL/6tHqy6sxVSWBV+EBtvqqSJftQc2r4lDtbWkj9hiBTg/P8s67UH+hdHlaSkqMzs+LPBwwn/RlmbujyYxaaSPRmlW4pI7YRn1NY3+cBqwXHVae7WMDPpx3VazTYgwCWvqAkW0KnSBg7EYQ5nEqD6D2Up7FJhOeRvdVNLWuwtgJmWxM5HKJTT0iHCtoogardfqajTDBtAeRIEDIk0lw6J47Yp5RBT5ED8c88j+hTAYROw2FJ+nHAQpI3TCGT/JtD6VlqebQ91SfTvdhXxT+tWGiOc95wGsh34dsN4jWVxkq2v9F3jEQ8nbZbE0b9OYWCZK/D86jDEz7AJ3JL9C5Cqv+SmtK7aMCdqp43+7323bP1dnR/XqCGRvDrpuBs/Vz2DCXO/SFE/jfeQOEBPlYt8ad0wCB3f1lExys/rtQ/N713GRPIh4NETS84qLxkKhYybBsezpmulPNL7KdAL3hypX9lvvCmIBMWQXGJbhROrz2yz7aoolmpWZ1ZV/38i1mwWEIidBgLovKSwKfV44ohC7KEyNwySS2L8XnB6Hzhmfgst9CoCiW713uONpKbtjEmM3CfGZGQXkqTpJQuNwBkpMg8iW4VpUBIS6CNR6xE9yFVOMaOnX7GsG2bDt+x4x38=
  - secure: hc3Q707RZ5u0SsITqQbSEQAdgmvUTrihI5G1b4B3XxbGgaQ2Tj9tsIHLoc4+C2EqUyN8F3CmXDIeDTKDN4EoKTh7MRPnUTCVhL7u/B4oUjJXtzjZuHjCuBw36/tiafuvAkIweDnfexbFBHzQM2bX+Xt96oKWy9VvhyshQ2bHHn7K61FdDH+NJO1nwOZj56dHEY2vYZcfRtsmH6STYK7Ta3ZwNHBkaFIYJ2EYGud8EIx4kw+0tmx64VaXXhtgRUChyxEBkt2HAsoipVV6EvYMKjuhRUafzcpY49Jqu7dTP/UZgjEsPl/lP+3yGZnqWVtWr+bBhANeg5N4lg+0PiYtwFrmYqNDBmmGHeS6+/m/RGW1xOOGj1iMWoe9AP5sClq1rVDR++lrcbZbnoWtw6/jtDuTf+rQNZbadOwcuCJt6ftWXiTYt5Qf4tJPKfjoMrDLtEPURdLJgl6vHfCghj35tni6jWZg7BIB9v3VMDiGCG9TJ4QsLHACKkvj084EHq/T0j+csl8VbyyyYvSbvjYC4pJyMk/TaJmgT+HPBxB0RbfC1IaLLnagZmlywvUHOwiCPlq7UCXjr00G+IIfuOPXuuY0CQuUSBxFqRiEvRm8vygtcTB0Qw/X1PXMhn1j5PglsnSNGAld/NxsjJbfR/xv9U3dH36yPPAEIup31iP86g0=
deploy:
- provider: script
  script: ./gradlew bintrayUpload --info
  skip_cleanup: true
  on:
    tags: true
- provider: releases
  api_key:
    secure: Yn/LzWkLp7ho0nemFOLBrwdjKeIjmCDHwGDUpGqzghsbEHrU2rfAR/uQDDqDZSwL+rJLdUugULLP1eG/VbzKJXpA7rOmfZ2GzuVDWbDAtMrFVSri9PYFcun9nnsthANZ6V098iDgiES/Kf/bLuOKCEjRDSfPfHtcO0PleCa2zOfr5cgeGMpRlwXTbDEhliviG8yHmp4Is1JNHd3CTjeevHscdr3UIzl4DBHlGAHh1yfI+BnicWI5/hDnw5T1KKVlWpe5PWAIbgrnabzvc7amV+EpRNxMtZ+p6qkcteXow8d9C5Yws0vZry9my8n467I76388wEIIGjMuS1jWk+VYhdPO5AuYJb+SO2QY0G6+VymE4KgDMHw8fLhUoKeFceMMTlpk4CiZIDlXQxrLFmWj53P31dfWP/OF4G05skDi5Fp1U37Fbiat3i3WomhrIgdA1mGyf9CbtqpD1A2Mbt19kUz0ZHMDCtxRkOw1ALFzzhdLolJy6WwmhmErmiZEO5E2RKMMdoXVx8elsjphnxekcJ8qRyHlQ/bpm3vG27Vzfm3HgBylTwXQ0gWvlHcVLD98OrsQNtQvPcfTcvu3DRvDAJvySS7LhCI9SNH28nfBUpebi0gYflvC9crHSGNk+z3kDrGnO1RT4S2pta47i7iHfhhneAgX5/d1QyJDQ3X7chg=
  file_glob: true
  file: build/libs/service-auth-provider-*.jar
  skip_cleanup: true
  on:
    repo: hmcts/service-auth-provider-java-client
    tags: true
